### ISSUE TITLE
An issue with installing praw in Ubuntu via pip

### ISSUE THREAD

**Issue by SynedraAcus** [ssimunic/Daily-Reddit-Wallpaper#33]
For me (Ubuntu 14.04LTS, python 2.6.7) `sudo pip install praw` or installing it with `requirements.txt` does not work. Using `sudo python -m pip install praw` works just fine. Sure, it's not an issue with your script, but if other users experience it as well, it'd be better to use `python -m pip` method in `README.md`. Complete log below.
```
morozov@pozdnyak-desktop:~/tools/Daily-Reddit-Wallpaper-master$ sudo pip install -r requirements.txt 
[sudo] password for morozov: 
The directory '/home/morozov/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/morozov/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting decorator==4.0.10 (from -r requirements.txt (line 1))
  Downloading decorator-4.0.10-py2.py3-none-any.whl
Collecting future==0.15.2 (from -r requirements.txt (line 2))
  Downloading future-0.15.2.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 49kB/s 
Collecting praw==3.5.0 (from -r requirements.txt (line 3))
  Downloading praw-3.5.0-py2.py3-none-any.whl (69kB)
    100% |████████████████████████████████| 71kB 41kB/s 
Collecting requests==2.10.0 (from -r requirements.txt (line 4))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 164kB/s 
Collecting six==1.10.0 (from -r requirements.txt (line 5))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting update-checker==0.11 (from -r requirements.txt (line 6))
  Downloading update_checker-0.11-py2.py3-none-any.whl
Installing collected packages: decorator, future, six, requests, update-checker, praw
  Running setup.py install for future ... done
  Found existing installation: six 1.5.2
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.5.2:
      Successfully uninstalled six-1.5.2
  Found existing installation: requests 2.13.0
    Uninstalling requests-2.13.0:
      Successfully uninstalled requests-2.13.0
Successfully installed decorator-4.0.10 future-0.15.2 praw-3.5.0 requests-2.10.0 six-1.10.0 update-checker-0.11
morozov@pozdnyak-desktop:~/tools/Daily-Reddit-Wallpaper-master$ ./change_wallpaper_reddit.py 
Traceback (most recent call last):
  File "./change_wallpaper_reddit.py", line 7, in <module>
    import praw
ImportError: No module named praw 
morozov@pozdnyak-desktop:~/tools/Daily-Reddit-Wallpaper-master$ python
Python 2.7.6 (default, Oct 26 2016, 20:32:47) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import praw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named praw
>>> 
morozov@pozdnyak-desktop:~/tools/Daily-Reddit-Wallpaper-master$ sudo pip install praw
The directory '/home/morozov/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/morozov/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: praw in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.4/dist-packages (from praw)
Requirement already satisfied: decorator<4.1,>=4.0.9 in /usr/local/lib/python3.4/dist-packages (from praw)
Requirement already satisfied: update-checker==0.11 in /usr/local/lib/python3.4/dist-packages (from praw)
Requirement already satisfied: six==1.10 in /usr/local/lib/python3.4/dist-packages (from praw)
morozov@pozdnyak-desktop:~/tools/Daily-Reddit-Wallpaper-master$ python
Python 2.7.6 (default, Oct 26 2016, 20:32:47) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import praw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named praw
```

**Comment by Justinzobel** [comment]
This version works https://github.com/markubiak/wallpaper-reddit
